export { h } from "./h.js"
export { renderSlots } from "./helpers/renderSlots.js"
export { createTextVNode } from "./vnode.js"
export { getCurrentInstance } from "./component.js"
export { provide, inject } from "./apiInject.js"
export { ref } from "../reactivity/Vue.js"
export { createRenderer } from "./renderer.js"
export { nextTick } from "./scheduler.js"